{{- if .Values.dbt.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dbt.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dbt.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io.managed-by: {{ .Release.Service }}
    owner: {{ .Values.dbt.deployment.metadata.labels.owner | toString }}
    app.kubernetes.io/component: {{ .Values.dbt.deployment.metadata.labels.component | toString }}
    app.kubernetes.io/part-of: {{ .Values.dbt.deployment.metadata.labels.part_of | toString }}
  namespace: {{ .Values.namespace }}
data:
  CLICKHOUSE_SERVICE_ADDRESS: "{{ .Values.dbt.configmap.svcHost }}"
{{- end }}