apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dbt.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "dbt.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    owner: {{ .Values.deployment.metadata.labels.owner | toString}}
    app.kubernetes.io/component: {{ .Values.deployment.metadata.labels.component | toString }}
    app.kubernetes.io/part-of: {{ .Values.deployment.metadata.labels.part_of | toString }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dbt.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.maxSurge }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dbt.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "dbt.name" . }}
        {{- if .Values.deployment.resources.enabled }}
        resources:
          limits:
            cpu: {{ .Values.deployment.resources.limits.cpu }}
            memory: {{ .Values.deployment.resources.limits.memory }}
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu }}
            memory: {{ .Values.deployment.resources.requests.memory }}
        {{- end }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        ports:
        - containerPort: {{ .Values.deployment.ports.port }}
        securityContext:
          privileged: {{ .Values.deployment.securityContext.privileged }}
          runAsUser: {{ .Values.deployment.securityContext.runAsUser }}
          runAsNonRoot: {{ .Values.deployment.securityContext.runAsNonRoot }}
        {{- if .Values.deployment.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command: {{ .Values.deployment.livenessProbe.exec.command }}
          initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.deployment.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command: {{ .Values.deployment.readinessProbe.exec.command }}
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
        {{- end }}
