apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbt.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dbt.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    owner: {{ .Values.dbt.deployment.metadata.labels.owner | toString }}
    app.kubernetes.io/component: {{ .Values.dbt.deployment.metadata.labels.component | toString }}
    app.kubernetes.io/part-of: {{ .Values.dbt.deployment.metadata.labels.part_of | toString }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "dbt.name" . }}
  ports:
    - name: {{ .Values.dbt.service.ports.http.name }}
      port: {{ .Values.dbt.service.ports.http.port }}
      targetPort: {{ .Values.dbt.service.ports.http.targetPort }}
  type: {{ .Values.dbt.service.type }}