{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.statefulset.name }}
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Values.namespace }}
data:
  CLICKHOUSE_SVC_HOST: "{{ .Values.configmap.svcHost }}"
  CLICKHOUSE_PORT: "{{ .Values.configmap.port }}"
{{- end -}}