{{- if .Values.deployment.enabled }}
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: clickhouse
   namespace: {{ .Values.namespace }}
   labels:
     #app: {{ .Values.clickhouse.deployment.name }}
     app.kubernetes.io/name: {{ include "clickhouse.name" . }}
     app.kubernetes.io/instance: {{ .Release.Name }}
     app.kubernetes.io/managed-by: {{ .Release.Service }}
 spec:
   replicas: {{ .Values.deployment.replicas }}
   selector:
     matchLabels:
       #app: {{ .Values.clickhouse.deployment.name }}
       app.kubernetes.io/name: {{ include "clickhouse.name" . }}
       app.kubernetes.io/instance: {{ .Release.Name }}
   strategy:
     type: {{ .Values.deployment.strategy.type }}
     rollingUpdate:
       maxSurge: {{ .Values.deployment.strategy.maxSurge }}
   template:
     metadata:
       labels:
         #app: {{ .Values.deployment.name }}
         app.kubernetes.io/name: {{ include "clickhouse.name" . }}
         app.kubernetes.io/instance: {{ .Release.Name }}
     spec:
       containers:
       - name: {{ include "clickhouse.name" . }}
         image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
         env:
           - name: CLICKHOUSE_USER
             valueFrom:
               secretKeyRef:
                 name: {{ include "clickhouse.name" .}}
                 key: CLICKHOUSE_USER
           - name: CLICKHOUSE_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: {{ include "clickhouse.name" .}}
                 key: CLICKHOUSE_PASSWORD
           - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
             valueFrom:
               secretKeyRef:
                 name: {{ include "clickhouse.name" .}}
                 key: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
         ports:
         - containerPort: {{ .Values.deployment.ports.port1 }}
         - containerPort: {{ .Values.deployment.ports.port2 }}
         - containerPort: {{ .Values.deployment.ports.port3 }}
{{- end }}
