apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  CLICKHOUSE_USER: #<base64-encoded-username>
  CLICKHOUSE_PASSWORD: #<base64-encoded-password>
  CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: MQ==