{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    #app: {{ .Values.deployment.name }}
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: {{ .Values.service.ports.http.name }}
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
    - name: {{ .Values.service.ports.tcp.name }}
      port: {{ .Values.service.ports.tcp.port }}
      targetPort: {{ .Values.service.ports.tcp.targetPort }}
  type: {{ .Values.service.type }}
{{- end }}