{{- if .Values.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clickhouse.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "clickhouse-statefulset"
  replicas: {{ .Values.statefulset.spec.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clickhouse.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  updateStrategy:
    type: {{ .Values.statefulset.spec.updateStrategy.type }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "clickhouse.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }} 
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      containers:
        - name: {{ .Values.statefulset.name }}
          image: "{{ .Values.statefulset.spec.image.repository }}:{{ .Values.statefulset.spec.image.tag }}"
          ports:
            - containerPort: {{ .Values.statefulset.spec.ports.port1 }}
            - containerPort: {{ .Values.statefulset.spec.ports.port2 }}
            - containerPort: {{ .Values.statefulset.spec.ports.port3 }}
          {{- if .Values.statefulset.spec.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command: {{ .Values.statefulset.spec.readinessProbe.exec.command }}
            initialDelaySeconds: {{ .Values.statefulset.spec.readinessProbe.initialDelaySeconds }}
          {{- end }}
          {{- if .Values.statefulset.spec.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command: {{ .Values.statefulset.spec.livenessProbe.exec.command }}
            initialDelaySeconds: {{ .Values.statefulset.spec.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.statefulset.spec.livenessProbe.periodSeconds }}
          {{- end }}
          env:
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "clickhouse.name" . }}
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "clickhouse.name" . }}
                  key: CLICKHOUSE_PASSWORD
            - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
              valueFrom:
                secretKeyRef:
                  name: {{ include "clickhouse.name" . }}
                  key: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
          volumeMounts:
            - name: {{ .Values.statefulset.spec.volumeMounts.name }}
              mountPath: {{ .Values.statefulset.spec.volumeMounts.mountPath }}
      volumes:
        - name: {{ .Values.statefulset.spec.volumes.name }}
          hostPath:
            path: {{ .Values.statefulset.spec.volumes.hostPath.path }}
            type: DirectoryOrCreate
{{- end }}